name: SignTransfer
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
main: RTG\SignTransfer\Loader
author: IG
permissions:
    transfersign.create:
        default: op
